import "./globals.css";
import { Navigation } from "./ui/components";
import { barlow } from "./ui/fonts/fonts";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={barlow.className}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
